name: Test School Python 02

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches: ["main", "master"]
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up authentication
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global http.extraheader "Authorization: Bearer $GITHUB_TOKEN"

      - name: Run your script
        run: |
          # Example Python script or other commands
          python your_script.py